services:

  postgres:
    image: postgres:16
    container_name: uxswarm-postgres
    restart: always
    environment:
      POSTGRES_DB: swarmDB
      POSTGRES_USER: swarm
      POSTGRES_PASSWORD: "0000"
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U swarm -d swarmDB"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: uxswarm-app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: swarmDB
      DB_USERNAME: swarm
      DB_PASSWORD: 0000
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data: